version: "2.1"

services:
  get-server-secrets:
    image: cgswong/aws:aws
    volumes:
      - ./server:/workspace
    working_dir: /workspace
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_SECRETS_BUCKET: ${S3_SECRETS_BUCKET}
    command: s3 cp s3://$S3_SECRETS_BUCKET ./.deploy --recursive

  deploy-server:
    build:
      context: ./server
      dockerfile: meteor-command.Dockerfile
    volumes:
      - ./server:/workspace
    working_dir: /workspace/.deploy
    command: bash -c "mup setup && mup deploy"

  test-server:
    build:
      context: ./server
      dockerfile: meteor-command.Dockerfile
    volumes:
      - ./server:/workspace
    working_dir: /workspace
    command: /bin/bash -c "meteor npm install && meteor test --once --driver-package dispatch:mocha"

  build-worker:
    build:
      context: ./server
      dockerfile: meteor-command.Dockerfile
    volumes:
      - ./worker:/workspace
      - ./.pkg-cache:/root/.pkg-cache
    working_dir: /workspace
    command: /bin/sh -c "npm install && pkg --out-path dist ."

  deploy-worker:
    image: cgswong/aws:aws
    volumes:
      - ./worker:/workspace
    working_dir: /workspace
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_WORKER_BIN_BUCKET: ${S3_WORKER_BIN_BUCKET}
    command: s3 cp dist s3://$S3_WORKER_BIN_BUCKET --recursive

  deploy-infrastructure:
    image: hashicorp/terraform:0.9.4
    volumes:
      - ./infrastructure:/workspace
      - $HOME/.ssh:/root/.ssh
    working_dir: /workspace
    environment:
      TF_VAR_aws_access_key: ${AWS_ACCESS_KEY_ID}
      TF_VAR_aws_secret_key: ${AWS_SECRET_ACCESS_KEY}
      TF_VAR_aws_region: ${AWS_REGION}
    entrypoint: /bin/sh
    command: -c "terraform init && terraform apply"
