version: "2.1"

services:
  get-server-secrets:
    image: cgswong/aws:aws
    volumes:
      - ./server:/workspace
    working_dir: /workspace
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    command: s3 cp s3://cas-spec-queue-secrets ./.deploy --recursive

  deploy-server:
    build:
      context: ./server
      dockerfile: meteor-command.Dockerfile
    volumes:
      - ./server:/workspace
    working_dir: /workspace/.deploy
    command: bash -c "mup setup && mup deploy"

  test-server:
    build:
      context: ./server
      dockerfile: meteor-command.Dockerfile
    volumes:
      - ./server:/workspace
    working_dir: /workspace
    command: /bin/bash -c "meteor npm install && meteor test --once --driver-package dispatch:mocha"

  build-worker:
    build:
      context: ./server
      dockerfile: meteor-command.Dockerfile
    volumes:
      - ./worker:/workspace
      - ./.pkg-cache:/root/.pkg-cache
    working_dir: /workspace
    command: pkg --out-path dist .

  deploy-worker:
    image: cgswong/aws:aws
    volumes:
      - ./worker:/workspace
    working_dir: /workspace
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    command: s3 cp dist s3://cas-spec-queue-bin --recursive
